// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/callback": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/dh/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/rdap-requests": {
    params: {};
  };
  "/dataholder": {
    params: {};
  };
  "/data-holders": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/forgot-password" | "/reset-password" | "/callback" | "/api/*" | "/dh/*" | "/dashboard" | "/rdap-requests" | "/dataholder" | "/data-holders" | "/logs" | "/*";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.jsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/forgot-password.jsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.jsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/callback.jsx": {
    id: "routes/callback";
    page: "/callback";
  };
  "routes/api.$.jsx": {
    id: "routes/api.$";
    page: "/api/*";
  };
  "routes/dh.$.jsx": {
    id: "routes/dh.$";
    page: "/dh/*";
  };
  "routes/protected.jsx": {
    id: "routes/protected";
    page: "/" | "/dashboard" | "/rdap-requests" | "/dataholder";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/rdap-requests.jsx": {
    id: "routes/rdap-requests";
    page: "/rdap-requests";
  };
  "routes/dataholder.jsx": {
    id: "routes/dataholder";
    page: "/dataholder";
  };
  "routes/admin.jsx": {
    id: "routes/admin";
    page: "/data-holders" | "/logs";
  };
  "routes/data-holders.jsx": {
    id: "routes/data-holders";
    page: "/data-holders";
  };
  "routes/logs.jsx": {
    id: "routes/logs";
    page: "/logs";
  };
  "routes/not-found.jsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/logout": typeof import("./app/routes/logout.jsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.jsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.jsx");
  "routes/callback": typeof import("./app/routes/callback.jsx");
  "routes/api.$": typeof import("./app/routes/api.$.jsx");
  "routes/dh.$": typeof import("./app/routes/dh.$.jsx");
  "routes/protected": typeof import("./app/routes/protected.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.jsx");
  "routes/rdap-requests": typeof import("./app/routes/rdap-requests.jsx");
  "routes/dataholder": typeof import("./app/routes/dataholder.jsx");
  "routes/admin": typeof import("./app/routes/admin.jsx");
  "routes/data-holders": typeof import("./app/routes/data-holders.jsx");
  "routes/logs": typeof import("./app/routes/logs.jsx");
  "routes/not-found": typeof import("./app/routes/not-found.jsx");
};