/*
 * SPDX-FileCopyrightText: 2025-2026 Edgemoor Research Institute and Derek Jenkins
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Author: Derek Jenkins <derek@pure-code.net>
 * Additional terms under AGPL-3.0 Section 7 apply. See NOTICE at the repository root.
 */

/**
 * ICANN's country/territory list, with the ICANN geographic region each belongs to.
 * The region is what the country picker groups by.
 */

export const COUNTRY_REGIONS = [
  { code: 'AF', label: 'Africa' },
  { code: 'AP', label: 'Asia / Australia / Pacific' },
  { code: 'EUR', label: 'Europe' },
  { code: 'LAC', label: 'Latin America / Caribbean' },
  { code: 'NA', label: 'North America' },
];

export const RDRS_COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', region: 'AP' },
  { code: 'AX', name: 'Åland Islands', region: 'EUR' },
  { code: 'AL', name: 'Albania', region: 'EUR' },
  { code: 'DZ', name: 'Algeria', region: 'AF' },
  { code: 'AS', name: 'American Samoa', region: 'NA' },
  { code: 'AD', name: 'Andorra', region: 'EUR' },
  { code: 'AO', name: 'Angola', region: 'AF' },
  { code: 'AI', name: 'Anguilla', region: 'EUR' },
  { code: 'AQ', name: 'Antarctica', region: 'AP' },
  { code: 'AG', name: 'Antigua and Barbuda', region: 'LAC' },
  { code: 'AR', name: 'Argentina', region: 'LAC' },
  { code: 'AM', name: 'Armenia', region: 'AP' },
  { code: 'AW', name: 'Aruba', region: 'EUR' },
  { code: 'AC', name: 'Ascension Island', region: 'EUR' },
  { code: 'AU', name: 'Australia', region: 'AP' },
  { code: 'AT', name: 'Austria', region: 'EUR' },
  { code: 'AZ', name: 'Azerbaijan', region: 'AP' },
  { code: 'BS', name: 'Bahamas', region: 'LAC' },
  { code: 'BH', name: 'Bahrain', region: 'AP' },
  { code: 'BD', name: 'Bangladesh', region: 'AP' },
  { code: 'BB', name: 'Barbados', region: 'LAC' },
  { code: 'BY', name: 'Belarus', region: 'EUR' },
  { code: 'BE', name: 'Belgium', region: 'EUR' },
  { code: 'BZ', name: 'Belize', region: 'LAC' },
  { code: 'BJ', name: 'Benin', region: 'AF' },
  { code: 'BM', name: 'Bermuda', region: 'EUR' },
  { code: 'BT', name: 'Bhutan', region: 'AP' },
  { code: 'BO', name: 'Plurinational State of Bolivia', label: 'Bolivia, Plurinational State of', region: 'LAC' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', region: 'LAC' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'EUR' },
  { code: 'BW', name: 'Botswana', region: 'AF' },
  { code: 'BV', name: 'Bouvet Island', region: 'EUR' },
  { code: 'BR', name: 'Brazil', region: 'LAC' },
  { code: 'IO', name: 'British Indian Ocean Territory', region: 'EUR' },
  { code: 'BN', name: 'Brunei Darussalam', region: 'AP' },
  { code: 'BG', name: 'Bulgaria', region: 'EUR' },
  { code: 'BF', name: 'Burkina Faso', region: 'AF' },
  { code: 'BI', name: 'Burundi', region: 'AF' },
  { code: 'KH', name: 'Cambodia', region: 'AP' },
  { code: 'CM', name: 'Cameroon', region: 'AF' },
  { code: 'CA', name: 'Canada', region: 'NA' },
  { code: 'CV', name: 'Cabo Verde', region: 'AF' },
  { code: 'KY', name: 'Cayman Islands', region: 'EUR' },
  { code: 'CF', name: 'Central African Republic', region: 'AF' },
  { code: 'TD', name: 'Republic of Chad', label: 'Chad, Republic of', region: 'AF' },
  { code: 'CL', name: 'Chile', region: 'LAC' },
  { code: 'CN', name: 'China', region: 'AP' },
  { code: 'CX', name: 'Christmas Island', region: 'AP' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', region: 'AP' },
  { code: 'CO', name: 'Colombia', region: 'LAC' },
  { code: 'KM', name: 'Comoros', region: 'AF' },
  { code: 'CG', name: 'Republic of Congo', label: 'Congo, Republic of', region: 'AF' },
  { code: 'CD', name: 'The Democratic Republic of the Congo', label: 'Congo, The Democratic Republic of the', region: 'AF' },
  { code: 'CK', name: 'Cook Islands', region: 'AP' },
  { code: 'CR', name: 'Costa Rica', region: 'LAC' },
  { code: 'CI', name: 'Côte d\'Ivoire', label: 'Côte d\'Ivoire', region: 'AF' },
  { code: 'HR', name: 'Croatia', region: 'EUR' },
  { code: 'CU', name: 'Cuba', region: 'LAC' },
  { code: 'CW', name: 'Curaçao', region: 'EUR' },
  { code: 'CY', name: 'Cyprus', region: 'AP' },
  { code: 'CZ', name: 'Czech Republic', region: 'EUR' },
  { code: 'DK', name: 'Denmark', region: 'EUR' },
  { code: 'DJ', name: 'Djibouti', region: 'AF' },
  { code: 'DM', name: 'The Commonwealth of Dominica', label: 'Dominica, The Commonwealth of', region: 'LAC' },
  { code: 'DO', name: 'Dominican Republic', region: 'LAC' },
  { code: 'EC', name: 'Ecuador', region: 'LAC' },
  { code: 'EG', name: 'Egypt', region: 'AF' },
  { code: 'SV', name: 'El Salvador', region: 'LAC' },
  { code: 'GQ', name: 'Equatorial Guinea', region: 'AF' },
  { code: 'ER', name: 'Eritrea', region: 'AF' },
  { code: 'EE', name: 'Estonia', region: 'EUR' },
  { code: 'SZ', name: 'Eswatini', region: 'AF' },
  { code: 'ET', name: 'Ethiopia', region: 'AF' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', region: 'EUR' },
  { code: 'FO', name: 'Faroe Islands', region: 'EUR' },
  { code: 'FJ', name: 'Fiji', region: 'AP' },
  { code: 'FI', name: 'Finland', region: 'EUR' },
  { code: 'FR', name: 'France', region: 'EUR' },
  { code: 'GF', name: 'French Guiana', region: 'EUR' },
  { code: 'PF', name: 'French Polynesia', region: 'EUR' },
  { code: 'TF', name: 'French Southern Territories', region: 'EUR' },
  { code: 'GA', name: 'Gabon', region: 'AF' },
  { code: 'GM', name: 'Republic of Gambia', label: 'Gambia, Republic of', region: 'AF' },
  { code: 'GE', name: 'Georgia', region: 'AP' },
  { code: 'DE', name: 'Germany', region: 'EUR' },
  { code: 'GH', name: 'Ghana', region: 'AF' },
  { code: 'GI', name: 'Gibraltar', region: 'EUR' },
  { code: 'GR', name: 'Greece', region: 'EUR' },
  { code: 'GL', name: 'Greenland', region: 'EUR' },
  { code: 'GD', name: 'Grenada', region: 'LAC' },
  { code: 'GP', name: 'Guadeloupe', region: 'EUR' },
  { code: 'GU', name: 'Guam', region: 'NA' },
  { code: 'GT', name: 'Guatemala', region: 'LAC' },
  { code: 'GG', name: 'Guernsey', region: 'EUR' },
  { code: 'GN', name: 'Republic of Guinea', label: 'Guinea, Republic of', region: 'AF' },
  { code: 'GW', name: 'Guinea-Bissau', region: 'AF' },
  { code: 'GY', name: 'Guyana', region: 'LAC' },
  { code: 'HT', name: 'Haiti', region: 'LAC' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', region: 'AP' },
  { code: 'VA', name: 'Holy See (Vatican City State)', region: 'EUR' },
  { code: 'HN', name: 'Honduras', region: 'LAC' },
  { code: 'HK', name: 'Hong Kong, China', region: 'AP' },
  { code: 'HU', name: 'Hungary', region: 'EUR' },
  { code: 'IS', name: 'Iceland', region: 'EUR' },
  { code: 'IN', name: 'India', region: 'AP' },
  { code: 'ID', name: 'Indonesia', region: 'AP' },
  { code: 'IR', name: 'Islamic Republic of Iran', label: 'Iran, Islamic Republic of', region: 'AP' },
  { code: 'IQ', name: 'Iraq', region: 'AP' },
  { code: 'IE', name: 'Ireland', region: 'EUR' },
  { code: 'IM', name: 'Isle of Man', region: 'EUR' },
  { code: 'IL', name: 'Israel', region: 'AP' },
  { code: 'IT', name: 'Italy', region: 'EUR' },
  { code: 'JM', name: 'Jamaica', region: 'LAC' },
  { code: 'JP', name: 'Japan', region: 'AP' },
  { code: 'JE', name: 'Jersey', region: 'EUR' },
  { code: 'JO', name: 'Jordan', region: 'AP' },
  { code: 'KZ', name: 'Kazakhstan', region: 'AP' },
  { code: 'KE', name: 'Kenya', region: 'AF' },
  { code: 'KI', name: 'Kiribati', region: 'AP' },
  { code: 'KP', name: 'Democratic People\'s Republic of Korea', label: 'Korea, Democratic People\'s Republic of', region: 'AP' },
  { code: 'KR', name: 'Republic of Korea', label: 'Korea, Republic of', region: 'AP' },
  { code: 'KW', name: 'Kuwait', region: 'AP' },
  { code: 'KG', name: 'Kyrgyz Republic', region: 'AP' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic', label: 'Lao People\'s Democratic Republic', region: 'AP' },
  { code: 'LV', name: 'Latvia', region: 'EUR' },
  { code: 'LB', name: 'Lebanon', region: 'AP' },
  { code: 'LS', name: 'Lesotho', region: 'AF' },
  { code: 'LR', name: 'Liberia', region: 'AF' },
  { code: 'LY', name: 'Libya', region: 'AF' },
  { code: 'LI', name: 'Liechtenstein', region: 'EUR' },
  { code: 'LT', name: 'Lithuania', region: 'EUR' },
  { code: 'LU', name: 'Luxembourg', region: 'EUR' },
  { code: 'MO', name: 'Macao, China', region: 'AP' },
  { code: 'MG', name: 'Madagascar', region: 'AF' },
  { code: 'MW', name: 'Malawi', region: 'AF' },
  { code: 'MY', name: 'Malaysia', region: 'AP' },
  { code: 'MV', name: 'Maldives', region: 'AP' },
  { code: 'ML', name: 'Mali', region: 'AF' },
  { code: 'MT', name: 'Malta', region: 'EUR' },
  { code: 'MH', name: 'Republic of the Marshall Islands', label: 'Marshall Islands, Republic of the', region: 'AP' },
  { code: 'MQ', name: 'Martinique', region: 'EUR' },
  { code: 'MR', name: 'Mauritania', region: 'AF' },
  { code: 'MU', name: 'Mauritius', region: 'AF' },
  { code: 'YT', name: 'Mayotte', region: 'EUR' },
  { code: 'MX', name: 'Mexico', region: 'LAC' },
  { code: 'FM', name: 'Federated States of Micronesia', label: 'Micronesia, Federated States of', region: 'AP' },
  { code: 'MD', name: 'Republic of Moldova', label: 'Moldova, Republic of', region: 'EUR' },
  { code: 'MC', name: 'Monaco', region: 'EUR' },
  { code: 'MN', name: 'Mongolia', region: 'AP' },
  { code: 'ME', name: 'Montenegro', region: 'EUR' },
  { code: 'MS', name: 'Montserrat', region: 'EUR' },
  { code: 'MA', name: 'Morocco', region: 'AF' },
  { code: 'MZ', name: 'Mozambique', region: 'AF' },
  { code: 'MM', name: 'Republic of the Union of Myanmar', label: 'Myanmar, Republic of the Union of', region: 'AP' },
  { code: 'NA', name: 'Namibia', region: 'AF' },
  { code: 'NR', name: 'Nauru', region: 'AP' },
  { code: 'NP', name: 'Nepal', region: 'AP' },
  { code: 'NL', name: 'Netherlands', region: 'EUR' },
  { code: 'NC', name: 'New Caledonia', region: 'EUR' },
  { code: 'NZ', name: 'New Zealand', region: 'AP' },
  { code: 'NI', name: 'Nicaragua', region: 'LAC' },
  { code: 'NE', name: 'Niger', region: 'AF' },
  { code: 'NG', name: 'Nigeria', region: 'AF' },
  { code: 'NU', name: 'Niue', region: 'AP' },
  { code: 'NF', name: 'Norfolk Island', region: 'AP' },
  { code: 'MK', name: 'North Macedonia', region: 'EUR' },
  { code: 'MP', name: 'Northern Mariana Islands', region: 'NA' },
  { code: 'NO', name: 'Norway', region: 'EUR' },
  { code: 'OM', name: 'Oman', region: 'AP' },
  { code: 'PK', name: 'Pakistan', region: 'AP' },
  { code: 'PW', name: 'Palau', region: 'AP' },
  { code: 'PS', name: 'Palestine', region: 'AP' },
  { code: 'PA', name: 'Republic of Panama', label: 'Panama, Republic of', region: 'LAC' },
  { code: 'PG', name: 'Papua New Guinea', region: 'AP' },
  { code: 'PY', name: 'Paraguay', region: 'LAC' },
  { code: 'PE', name: 'Peru', region: 'LAC' },
  { code: 'PH', name: 'Philippines', region: 'AP' },
  { code: 'PN', name: 'Pitcairn', region: 'EUR' },
  { code: 'PL', name: 'Poland', region: 'EUR' },
  { code: 'PT', name: 'Portugal', region: 'EUR' },
  { code: 'PR', name: 'Puerto Rico', region: 'NA' },
  { code: 'QA', name: 'Qatar', region: 'AP' },
  { code: 'RE', name: 'Réunion', region: 'EUR' },
  { code: 'RO', name: 'Romania', region: 'EUR' },
  { code: 'RU', name: 'Russian Federation', region: 'EUR' },
  { code: 'RW', name: 'Rwanda', region: 'AF' },
  { code: 'BL', name: 'Saint Barthélemy', region: 'LAC' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', region: 'EUR' },
  { code: 'KN', name: 'Saint Kitts and Nevis', region: 'LAC' },
  { code: 'LC', name: 'Saint Lucia', region: 'LAC' },
  { code: 'MF', name: 'Saint Martin (French part)', region: 'LAC' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', region: 'EUR' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', region: 'LAC' },
  { code: 'WS', name: 'Samoa', region: 'AP' },
  { code: 'SM', name: 'San Marino', region: 'EUR' },
  { code: 'ST', name: 'Sao Tome and Principe', region: 'AF' },
  { code: 'SA', name: 'Saudi Arabia', region: 'AP' },
  { code: 'SN', name: 'Senegal', region: 'AF' },
  { code: 'RS', name: 'Serbia', region: 'EUR' },
  { code: 'SC', name: 'Seychelles', region: 'AF' },
  { code: 'SL', name: 'Sierra Leone', region: 'AF' },
  { code: 'SG', name: 'Singapore', region: 'AP' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', region: 'LAC' },
  { code: 'SK', name: 'Slovakia', region: 'EUR' },
  { code: 'SI', name: 'Slovenia', region: 'EUR' },
  { code: 'SB', name: 'Solomon Islands', region: 'AP' },
  { code: 'SO', name: 'Somalia', region: 'AF' },
  { code: 'ZA', name: 'South Africa', region: 'AF' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', region: 'EUR' },
  { code: 'SS', name: 'South Sudan', region: 'AF' },
  { code: 'ES', name: 'Spain', region: 'EUR' },
  { code: 'LK', name: 'Sri Lanka', region: 'AP' },
  { code: 'SD', name: 'Sudan', region: 'AF' },
  { code: 'SR', name: 'Republic of Suriname', label: 'Suriname, Republic of', region: 'LAC' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', region: 'EUR' },
  { code: 'SE', name: 'Sweden', region: 'EUR' },
  { code: 'CH', name: 'Switzerland', region: 'EUR' },
  { code: 'SY', name: 'Syrian Arab Republic', region: 'AP' },
  { code: 'TW', name: 'Chinese Taipei', label: 'Taipei, Chinese', region: 'AP' },
  { code: 'TJ', name: 'Tajikistan', region: 'AP' },
  { code: 'TZ', name: 'United Republic of Tanzania', label: 'Tanzania, United Republic of', region: 'AF' },
  { code: 'TH', name: 'Thailand', region: 'AP' },
  { code: 'TL', name: 'Timor-Leste', region: 'AP' },
  { code: 'TG', name: 'Togo', region: 'AF' },
  { code: 'TK', name: 'Tokelau', region: 'AP' },
  { code: 'TO', name: 'Tonga', region: 'AP' },
  { code: 'TT', name: 'Trinidad and Tobago', region: 'LAC' },
  { code: 'TN', name: 'Tunisia', region: 'AF' },
  { code: 'TR', name: 'Republic of Türkiye', label: 'Türkiye, Republic of', region: 'AP' },
  { code: 'TM', name: 'Turkmenistan', region: 'AP' },
  { code: 'TC', name: 'Turks and Caicos Islands', region: 'EUR' },
  { code: 'TV', name: 'Tuvalu', region: 'AP' },
  { code: 'UG', name: 'Uganda', region: 'AF' },
  { code: 'UA', name: 'Ukraine', region: 'EUR' },
  { code: 'AE', name: 'United Arab Emirates', region: 'AP' },
  { code: 'UK', name: 'United Kingdom of Great Britain and Northern Ireland', region: 'EUR' },
  { code: 'US', name: 'United States of America', region: 'NA' },
  { code: 'UM', name: 'United States Minor Outlying Islands', region: 'NA' },
  { code: 'UY', name: 'Uruguay', region: 'LAC' },
  { code: 'UZ', name: 'Uzbekistan', region: 'AP' },
  { code: 'VU', name: 'Vanuatu', region: 'AP' },
  { code: 'VE', name: 'Bolivarian Republic of Venezuela', label: 'Venezuela, Bolivarian Republic of', region: 'LAC' },
  { code: 'VN', name: 'Viet Nam', region: 'AP' },
  { code: 'VG', name: 'Virgin Islands, British', region: 'EUR' },
  { code: 'VI', name: 'Virgin Islands, U.S.', region: 'NA' },
  { code: 'WF', name: 'Wallis And Futuna', region: 'EUR' },
  { code: 'EH', name: 'Western Sahara', region: 'AF' },
  { code: 'YE', name: 'Yemen', region: 'AP' },
  { code: 'ZM', name: 'Zambia', region: 'AF' },
  { code: 'ZW', name: 'Zimbabwe', region: 'AF' },
];

export const countryLabel = (c) => c.label || c.name;

/**
 * The flag for an ISO 3166-1 alpha-2 code, built from regional indicator symbols.
 * Returns an empty string for anything that is not two A-Z letters, so a code the
 * list carries that has no flag renders as nothing rather than as tofu.
 */
export const countryFlag = (code) => {
  if (typeof code !== 'string' || !/^[A-Za-z]{2}$/.test(code)) return '';
  return code
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(0x1f1e6 + ch.charCodeAt(0) - 65));
};

/** The flag for a country stored by name, which is how these values are persisted. */
export const countryFlagByName = (name) => {
  if (!name) return '';
  const match = RDRS_COUNTRIES.find(c => c.name === name);
  return match ? countryFlag(match.code) : '';
};

export const RDRS_COUNTRY_CODES = [...new Set(RDRS_COUNTRIES.map(c => c.code))]
  .sort((a, b) => a.localeCompare(b));

export const RDRS_COUNTRY_NAMES = RDRS_COUNTRIES.map(c => c.name);

