// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/templates": {
    params: {};
  };
  "/subscriptions": {
    params: {};
  };
  "/data-holders": {
    params: {};
  };
  "/instances": {
    params: {};
  };
  "/applications": {
    params: {};
  };
  "/requestor-groups": {
    params: {};
  };
  "/data-holder-groups": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/audit-logs": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/join" | "/forgot-password" | "/reset-password" | "/login" | "/logout" | "/api/*" | "/dashboard" | "/templates" | "/subscriptions" | "/data-holders" | "/instances" | "/applications" | "/requestor-groups" | "/data-holder-groups" | "/users" | "/audit-logs" | "/*";
  };
  "routes/join.jsx": {
    id: "routes/join";
    page: "/join";
  };
  "routes/forgot-password.jsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.jsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.jsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/api.$.jsx": {
    id: "routes/api.$";
    page: "/api/*";
  };
  "routes/protected.jsx": {
    id: "routes/protected";
    page: "/" | "/dashboard" | "/templates" | "/subscriptions" | "/data-holders" | "/instances" | "/applications" | "/requestor-groups" | "/data-holder-groups" | "/users" | "/audit-logs";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/templates.jsx": {
    id: "routes/templates";
    page: "/templates";
  };
  "routes/subscriptions.jsx": {
    id: "routes/subscriptions";
    page: "/subscriptions";
  };
  "routes/data-holders.jsx": {
    id: "routes/data-holders";
    page: "/data-holders";
  };
  "routes/instances.jsx": {
    id: "routes/instances";
    page: "/instances";
  };
  "routes/applications.jsx": {
    id: "routes/applications";
    page: "/applications";
  };
  "routes/requestor-groups.jsx": {
    id: "routes/requestor-groups";
    page: "/requestor-groups";
  };
  "routes/data-holder-groups.jsx": {
    id: "routes/data-holder-groups";
    page: "/data-holder-groups";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/audit-logs.jsx": {
    id: "routes/audit-logs";
    page: "/audit-logs";
  };
  "routes/not-found.jsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/join": typeof import("./app/routes/join.jsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.jsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/logout": typeof import("./app/routes/logout.jsx");
  "routes/api.$": typeof import("./app/routes/api.$.jsx");
  "routes/protected": typeof import("./app/routes/protected.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.jsx");
  "routes/templates": typeof import("./app/routes/templates.jsx");
  "routes/subscriptions": typeof import("./app/routes/subscriptions.jsx");
  "routes/data-holders": typeof import("./app/routes/data-holders.jsx");
  "routes/instances": typeof import("./app/routes/instances.jsx");
  "routes/applications": typeof import("./app/routes/applications.jsx");
  "routes/requestor-groups": typeof import("./app/routes/requestor-groups.jsx");
  "routes/data-holder-groups": typeof import("./app/routes/data-holder-groups.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/audit-logs": typeof import("./app/routes/audit-logs.jsx");
  "routes/not-found": typeof import("./app/routes/not-found.jsx");
};