// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/domain/*": {
    params: {
      "*": string;
    };
  };
  "/ip/*": {
    params: {
      "*": string;
    };
  };
  "/autnum/*": {
    params: {
      "*": string;
    };
  };
  "/subscriptions": {
    params: {};
  };
  "/agreement-templates": {
    params: {};
  };
  "/agreements": {
    params: {};
  };
  "/agreement-requests": {
    params: {};
  };
  "/pending": {
    params: {};
  };
  "/data-holder-groups": {
    params: {};
  };
  "/policy": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/query": {
    params: {};
  };
  "/rdap-data": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/external-database": {
    params: {};
  };
  "/external-database/mapping": {
    params: {};
  };
  "/external-database/schema": {
    params: {};
  };
  "/external-database/browser": {
    params: {};
  };
  "/file-automation": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/forgot-password" | "/reset-password" | "/api/*" | "/domain/*" | "/ip/*" | "/autnum/*" | "/subscriptions" | "/agreement-templates" | "/agreements" | "/agreement-requests" | "/pending" | "/data-holder-groups" | "/policy" | "/logs" | "/query" | "/rdap-data" | "/settings" | "/users" | "/external-database" | "/external-database/mapping" | "/external-database/schema" | "/external-database/browser" | "/file-automation" | "/*";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.jsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/forgot-password.jsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.jsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/api.$.jsx": {
    id: "routes/api.$";
    page: "/api/*";
  };
  "routes/rdap-domain.$.jsx": {
    id: "routes/rdap-domain.$";
    page: "/domain/*";
  };
  "routes/rdap-ip.$.jsx": {
    id: "routes/rdap-ip.$";
    page: "/ip/*";
  };
  "routes/rdap-autnum.$.jsx": {
    id: "routes/rdap-autnum.$";
    page: "/autnum/*";
  };
  "routes/legacy-subscriptions.jsx": {
    id: "routes/legacy-subscriptions";
    page: "/subscriptions";
  };
  "routes/legacy-agreement-templates.jsx": {
    id: "routes/legacy-agreement-templates";
    page: "/agreement-templates";
  };
  "routes/legacy-agreements.jsx": {
    id: "routes/legacy-agreements";
    page: "/agreements";
  };
  "routes/legacy-agreement-requests.jsx": {
    id: "routes/legacy-agreement-requests";
    page: "/agreement-requests";
  };
  "routes/protected.jsx": {
    id: "routes/protected";
    page: "/" | "/pending" | "/data-holder-groups" | "/policy" | "/logs" | "/query" | "/rdap-data" | "/settings" | "/users" | "/external-database" | "/external-database/mapping" | "/external-database/schema" | "/external-database/browser" | "/file-automation";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/pending.jsx": {
    id: "routes/pending";
    page: "/pending";
  };
  "routes/data-holder-groups.jsx": {
    id: "routes/data-holder-groups";
    page: "/data-holder-groups";
  };
  "routes/policy.jsx": {
    id: "routes/policy";
    page: "/policy";
  };
  "routes/logs.jsx": {
    id: "routes/logs";
    page: "/logs";
  };
  "routes/query.jsx": {
    id: "routes/query";
    page: "/query";
  };
  "routes/rdap-data.jsx": {
    id: "routes/rdap-data";
    page: "/rdap-data";
  };
  "routes/settings.jsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/external-database.jsx": {
    id: "routes/external-database";
    page: "/external-database" | "/external-database/mapping" | "/external-database/schema" | "/external-database/browser";
  };
  "routes/external-database.index.jsx": {
    id: "routes/external-database.index";
    page: "/external-database";
  };
  "routes/external-database.mapping.jsx": {
    id: "routes/external-database.mapping";
    page: "/external-database/mapping";
  };
  "routes/external-database.schema.jsx": {
    id: "routes/external-database.schema";
    page: "/external-database/schema";
  };
  "routes/external-database.browser.jsx": {
    id: "routes/external-database.browser";
    page: "/external-database/browser";
  };
  "routes/file-automation.jsx": {
    id: "routes/file-automation";
    page: "/file-automation";
  };
  "routes/catch-all.jsx": {
    id: "routes/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/logout": typeof import("./app/routes/logout.jsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.jsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.jsx");
  "routes/api.$": typeof import("./app/routes/api.$.jsx");
  "routes/rdap-domain.$": typeof import("./app/routes/rdap-domain.$.jsx");
  "routes/rdap-ip.$": typeof import("./app/routes/rdap-ip.$.jsx");
  "routes/rdap-autnum.$": typeof import("./app/routes/rdap-autnum.$.jsx");
  "routes/legacy-subscriptions": typeof import("./app/routes/legacy-subscriptions.jsx");
  "routes/legacy-agreement-templates": typeof import("./app/routes/legacy-agreement-templates.jsx");
  "routes/legacy-agreements": typeof import("./app/routes/legacy-agreements.jsx");
  "routes/legacy-agreement-requests": typeof import("./app/routes/legacy-agreement-requests.jsx");
  "routes/protected": typeof import("./app/routes/protected.jsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.jsx");
  "routes/pending": typeof import("./app/routes/pending.jsx");
  "routes/data-holder-groups": typeof import("./app/routes/data-holder-groups.jsx");
  "routes/policy": typeof import("./app/routes/policy.jsx");
  "routes/logs": typeof import("./app/routes/logs.jsx");
  "routes/query": typeof import("./app/routes/query.jsx");
  "routes/rdap-data": typeof import("./app/routes/rdap-data.jsx");
  "routes/settings": typeof import("./app/routes/settings.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/external-database": typeof import("./app/routes/external-database.jsx");
  "routes/external-database.index": typeof import("./app/routes/external-database.index.jsx");
  "routes/external-database.mapping": typeof import("./app/routes/external-database.mapping.jsx");
  "routes/external-database.schema": typeof import("./app/routes/external-database.schema.jsx");
  "routes/external-database.browser": typeof import("./app/routes/external-database.browser.jsx");
  "routes/file-automation": typeof import("./app/routes/file-automation.jsx");
  "routes/catch-all": typeof import("./app/routes/catch-all.jsx");
};