/*
 * SPDX-FileCopyrightText: 2025-2026 Edgemoor Research Institute and Derek Jenkins
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Author: Derek Jenkins <derek@pure-code.net>
 * Additional terms under AGPL-3.0 Section 7 apply. See NOTICE at the repository root.
 */

package com.requestormanager.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Stores the Keycloak client credentials provisioned for a specific subscription.
 * Each active subscription gets a dedicated Keycloak client that the data holder
 * can use exclusively for token introspection on RDAP queries from the
 * associated requestor group.
 *
 * Lifecycle:
 *   1. Created when a subscription is activated (ACTIVE status)
 *   2. Sent to the data holder via POST /external/{requestId}/credentials
 *   3. Deleted (and Keycloak client removed) when a subscription is terminated
 */
@Entity
@Table(name = "subscription_credentials")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SubscriptionCredential {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The subscription request this credential was provisioned for
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subscription_request_id", nullable = false, unique = true)
    private SubscriptionRequest subscriptionRequest;

    /**
     * The Keycloak client ID created for this subscription
     * Format: sub-{internalRequestId}-introspect
     */
    @Column(name = "keycloak_client_id", nullable = false, unique = true)
    private String keycloakClientId;

    /**
     * The Keycloak internal UUID of the created client
     * (needed for management operations like update/delete)
     */
    @Column(name = "keycloak_client_uuid", nullable = false)
    private String keycloakClientUuid;

    /**
     * The client secret generated by Keycloak.
     * Stored encrypted/hashed in production — here stored as-is for dev.
     * Only needed if we need to re-send to the data holder.
     */
    @Column(name = "client_secret", nullable = false)
    private String clientSecret;

    /**
     * The introspection endpoint URL that the data holder should use
     * with these credentials.
     */
    @Column(name = "introspection_url", nullable = false)
    private String introspectionUrl;

    /**
     * The token endpoint URL (data holder may need this for client_credentials flow)
     */
    @Column(name = "token_url")
    private String tokenUrl;

    /**
     * Whether the credentials have been successfully delivered to the data holder
     */
    @Column(name = "delivered_to_dataholder", nullable = false)
    @Builder.Default
    private Boolean deliveredToDataholder = false;

    /**
     * When the credentials were delivered to the data holder
     */
    @Column(name = "delivered_at")
    private LocalDateTime deliveredAt;

    /**
     * Number of delivery attempts
     */
    @Column(name = "delivery_attempts", nullable = false)
    @Builder.Default
    private Integer deliveryAttempts = 0;

    /**
     * Last delivery error message (if failed)
     */
    @Column(name = "last_delivery_error", columnDefinition = "TEXT")
    private String lastDeliveryError;

    /**
     * Whether this credential is currently active
     */
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    /**
     * When the credential was revoked (if applicable)
     */
    @Column(name = "revoked_at")
    private LocalDateTime revokedAt;

    /**
     * Reason for revocation
     */
    @Column(name = "revocation_reason")
    private String revocationReason;

    // ==================== Audit Fields ====================

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}