// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/subscriptions": {
    params: {};
  };
  "/requestor-groups": {
    params: {};
  };
  "/data-holder-groups": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/forgot-password" | "/reset-password" | "/unauthorized" | "/api/*" | "/dashboard" | "/subscriptions" | "/requestor-groups" | "/data-holder-groups" | "/users" | "/*";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.jsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/forgot-password.jsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.jsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/unauthorized.jsx": {
    id: "routes/unauthorized";
    page: "/unauthorized";
  };
  "routes/api.$.jsx": {
    id: "routes/api.$";
    page: "/api/*";
  };
  "routes/protected.jsx": {
    id: "routes/protected";
    page: "/" | "/dashboard" | "/subscriptions" | "/requestor-groups" | "/data-holder-groups" | "/users";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/subscriptions.jsx": {
    id: "routes/subscriptions";
    page: "/subscriptions";
  };
  "routes/requestor-groups.jsx": {
    id: "routes/requestor-groups";
    page: "/requestor-groups";
  };
  "routes/data-holder-groups.jsx": {
    id: "routes/data-holder-groups";
    page: "/data-holder-groups";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/not-found.jsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/logout": typeof import("./app/routes/logout.jsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.jsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.jsx");
  "routes/unauthorized": typeof import("./app/routes/unauthorized.jsx");
  "routes/api.$": typeof import("./app/routes/api.$.jsx");
  "routes/protected": typeof import("./app/routes/protected.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.jsx");
  "routes/subscriptions": typeof import("./app/routes/subscriptions.jsx");
  "routes/requestor-groups": typeof import("./app/routes/requestor-groups.jsx");
  "routes/data-holder-groups": typeof import("./app/routes/data-holder-groups.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/not-found": typeof import("./app/routes/not-found.jsx");
};